SET SQL_SAFE_UPDATES = 0;
Update users set state = 'AL' where state = 'Alabama';
Update users set state = 'Ak' where state = 'Alaska';
Update users set state = 'AZ' where state = 'Arizona';
Update users set state = 'AR' where state = 'Arkansas';
Update users set state = 'CA' where state = 'California';
Update users set state = 'CO' where state = 'Colorado';
Update users set state = 'CT' where state = 'Connecticut';
Update users set state = 'DE' where state = 'Delaware';
Update users set state = 'DC' where state = 'District of Columbia';
Update users set state = 'FL' where state = 'Florida';
Update users set state = 'GA' where state = 'Georgia';
Update users set state = 'HI' where state = 'Hawaii';
Update users set state = 'ID' where state = 'Idaho';
Update users set state = 'IL' where state = 'Illinois';
Update users set state = 'IN' where state = 'Indiana';
Update users set state = 'IA' where state = 'Iowa';
Update users set state = 'KA' where state = 'Kansas';
Update users set state = 'KY' where state = 'Kentucky';
Update users set state = 'LA' where state = 'Louisiana';
Update users set state = 'ME' where state = 'Maine';
Update users set state = 'MD' where state = 'Maryland';
Update users set state = 'MA' where state = 'Massachusetts';
Update users set state = 'MI' where state = 'Michigan';
Update users set state = 'MN' where state = 'Minnesota';
Update users set state = 'MS' where state = 'Mississippi';
Update users set state = 'MO' where state = 'Missouri';
Update users set state = 'MT' where state = 'Montana';
Update users set state = 'NE' where state = 'Nebraska';
Update users set state = 'NV' where state = 'Nevada';
Update users set state = 'NH' where state = 'New Hampshire';
Update users set state = 'NJ' where state = 'New Jersey';
Update users set state = 'NM' where state = 'New Mexico';
Update users set state = 'NY' where state = 'New York';
Update users set state = 'NC' where state = 'North Carolina';
Update users set state = 'ND' where state = 'North Dakota';
Update users set state = 'OH' where state = 'Ohio';
Update users set state = 'OK' where state = 'Oklahoma';
Update users set state = 'OR' where state = 'Oregon';
Update users set state = 'PA' where state = 'Pennsylvania';
Update users set state = 'RI' where state = 'Rhode Island';
Update users set state = 'SC' where state = 'South Carolina';
Update users set state = 'SD' where state = 'South Dakota';
Update users set state = 'TN' where state = 'Tennessee';
Update users set state = 'TX' where state = 'Texas';
Update users set state = 'UT' where state = 'Utah';
Update users set state = 'VT' where state = 'Vermont';
Update users set state = 'VA' where state = 'Virginia';
Update users set state = 'WA' where state = 'Washington';
Update users set state = 'WV' where state = 'West Virginia';
Update users set state = 'WI' where state = 'Wisconsin';
Update users set state = 'WY' where state = 'Wyoming';

